### ISSUE TITLE
歌曲识别不了

### ISSUE THREAD

**Issue by woqichino** [lovegaoshi/ipynb#14]
| ERROR    | __main__:recognize_song:234 - An error has been caught in function 'recognize_song', process 'MainProcess' (24312), thread 'MainThread' (27912):
Traceback (most recent call last):

**Comment by lovegaoshi** [comment]
shazamapi似了，用https://pypi.org/project/shazamio/ 替代

**Comment by woqichino** [comment]
> shazamapi 好像了，用https://pypi.org/project/shazamio/替代

大佬，实在不好意思，我是小白，请问这个要怎么替代，能否更新一下那个新新教程。。。

**Comment by woqichino** [comment]
> > shazamapi 想要了，用[https://pypi.org/project/shazamio/替代](https://pypi.org/project/shazamio/%E6%9B%BF%E4%BB%A3)
> 
> 大佬，实在不好意思，我是小白，请问这个要怎么替代，能否更新一下那个新新教程。。。

**Comment by lovegaoshi** [comment]
换起来其实还挺麻烦的

在[docker版本](https://github.com/lovegaoshi/bili-music-segmenter/tree/inaseg-cloud)替换了
jupyter还在写
推荐用docker不要自己折腾环境 windows下看https://github.com/lovegaoshi/bili-music-segmenter/issues/9
