### ISSUE TITLE
[bug] shazam文件名过长问题

### ISSUE THREAD

**Issue by bakaz** [lovegaoshi/ipynb#17]
shazam_title下面的
titile与artist加一个[:50]？

**Comment by lovegaoshi** [comment]
fork以后[自己加叭](https://github.com/lovegaoshi/bili-music-segmenter/blob/4fc5cd9e0c8ecd4991f9925a1bf26063e812028f/segment/shazam.py#L102)
因为没有遇到b站文件名过长没法上传的原因，就不在主分支里修改了
